import { Match, Prediction, QuickAction, NewsItem } from './types';

export const LIVE_MATCHES: Match[] = [
  {
    id: '1',
    home: 'Brasil',
    away: 'Jerman',
    homeFlag: '🇧🇷',
    awayFlag: '🇩🇪',
    homeScore: 2,
    awayScore: 1,
    minute: 67,
    status: 'live',
    goalScorers: ['Neymar 32\'', 'Vinicius 58\'', 'Musiala 45+1\''],
    possession: { home: 48, away: 52 },
    shotsOnTarget: { home: 5, away: 4 },
  },
  {
    id: '2',
    home: 'Spanyol',
    away: 'Maroko',
    homeFlag: '🇪🇸',
    awayFlag: '🇲🇦',
    homeScore: 0,
    awayScore: 0,
    minute: 23,
    status: 'live',
    goalScorers: [],
    possession: { home: 61, away: 39 },
    shotsOnTarget: { home: 2, away: 1 },
  },
  {
    id: '3',
    home: 'Prancis',
    away: 'Senegal',
    homeFlag: '🇫🇷',
    awayFlag: '🇸🇳',
    homeScore: 1,
    awayScore: 0,
    minute: 45,
    status: 'live',
    goalScorers: ['Mbappé 38\''],
    possession: { home: 55, away: 45 },
    shotsOnTarget: { home: 4, away: 2 },
  },
];

export const PREDICTIONS: Record<string, Prediction> = {
  'brasil-jerman': {
    id: 'brasil-jerman',
    homeTeam: 'Brasil',
    awayTeam: 'Jerman',
    homeWin: 52,
    draw: 26,
    awayWin: 22,
    reasoning: 'Brasil menunjukkan performa konsisten dalam 5 pertandingan terakhir dengan 4 kemenangan. Formasi ofensif mereka sulit dihentikan.',
    factors: [
      { name: 'Form 5 Laga Terakhir', value: 80, icon: 'trending-up' },
      { name: 'Head-to-Head', value: 65, icon: 'git-compare' },
      { name: 'Kondisi Cuaca', value: 30, icon: 'cloud-sun' },
      { name: 'Strategi Taktik', value: 70, icon: 'target' },
      { name: 'Motivasi Tim', value: 90, icon: 'flame' },
    ],
    startingXI: {
      formation: '4-3-3',
      players: [
        { name: 'Alisson', position: 'GK', row: 0, col: 2 },
        { name: 'Danilo', position: 'RB', row: 1, col: 0 },
        { name: 'Marquinhos', position: 'CB', row: 1, col: 1 },
        { name: 'T. Silva', position: 'CB', row: 1, col: 3 },
        { name: 'Sandro', position: 'LB', row: 1, col: 4 },
        { name: 'Casemiro', position: 'CDM', row: 2, col: 1 },
        { name: 'Paquetá', position: 'CM', row: 2, col: 2 },
        { name: 'B. Guimarães', position: 'CM', row: 2, col: 3 },
        { name: 'Raphinha', position: 'RW', row: 3, col: 0 },
        { name: 'Richarlison', position: 'ST', row: 3, col: 2 },
        { name: 'Vinicius Jr', position: 'LW', row: 3, col: 4 },
      ],
    },
  },
  'argentina-maroko': {
    id: 'argentina-maroko',
    homeTeam: 'Argentina',
    awayTeam: 'Maroko',
    homeWin: 55,
    draw: 25,
    awayWin: 20,
    reasoning: 'Argentina dalam performa terbaik setelah juara Piala Dunia 2022. Messi masih menjadi pembeda utama.',
    factors: [
      { name: 'Form 5 Laga Terakhir', value: 85, icon: 'trending-up' },
      { name: 'Head-to-Head', value: 70, icon: 'git-compare' },
      { name: 'Kondisi Cuaca', value: 45, icon: 'cloud-sun' },
      { name: 'Strategi Taktik', value: 75, icon: 'target' },
      { name: 'Motivasi Tim', value: 95, icon: 'flame' },
    ],
    startingXI: {
      formation: '4-3-3',
      players: [
        { name: 'E. Martínez', position: 'GK', row: 0, col: 2 },
        { name: 'Molina', position: 'RB', row: 1, col: 0 },
        { name: 'Romero', position: 'CB', row: 1, col: 1 },
        { name: 'Otamendi', position: 'CB', row: 1, col: 3 },
        { name: 'Acuña', position: 'LB', row: 1, col: 4 },
        { name: 'De Paul', position: 'CDM', row: 2, col: 1 },
        { name: 'Mac Allister', position: 'CM', row: 2, col: 2 },
        { name: 'Fernández', position: 'CM', row: 2, col: 3 },
        { name: 'Messi', position: 'RW', row: 3, col: 0 },
        { name: 'Álvarez', position: 'ST', row: 3, col: 2 },
        { name: 'Di María', position: 'LW', row: 3, col: 4 },
      ],
    },
  },
  'prancis-senegal': {
    id: 'prancis-senegal',
    homeTeam: 'Prancis',
    awayTeam: 'Senegal',
    homeWin: 60,
    draw: 22,
    awayWin: 18,
    reasoning: 'Prancis memiliki kedalaman skuad terbaik dengan Mbappé dan Griezmann dalam performa puncak.',
    factors: [
      { name: 'Form 5 Laga Terakhir', value: 78, icon: 'trending-up' },
      { name: 'Head-to-Head', value: 72, icon: 'git-compare' },
      { name: 'Kondisi Cuaca', value: 40, icon: 'cloud-sun' },
      { name: 'Strategi Taktik', value: 82, icon: 'target' },
      { name: 'Motivasi Tim', value: 88, icon: 'flame' },
    ],
    startingXI: {
      formation: '4-2-3-1',
      players: [
        { name: 'Lloris', position: 'GK', row: 0, col: 2 },
        { name: 'Koundé', position: 'RB', row: 1, col: 0 },
        { name: 'Varane', position: 'CB', row: 1, col: 1 },
        { name: 'Upamecano', position: 'CB', row: 1, col: 3 },
        { name: 'Hernández', position: 'LB', row: 1, col: 4 },
        { name: 'Tchouaméni', position: 'CDM', row: 2, col: 1 },
        { name: 'Rabiot', position: 'CDM', row: 2, col: 3 },
        { name: 'Dembélé', position: 'RW', row: 3, col: 0 },
        { name: 'Griezmann', position: 'CAM', row: 3, col: 2 },
        { name: 'Mbappé', position: 'LW', row: 3, col: 4 },
        { name: 'Giroud', position: 'ST', row: 4, col: 2 },
      ],
    },
  },
};

export const QUICK_ACTIONS: QuickAction[] = [
  {
    id: 'live-scores',
    label: 'Skor Terkini',
    icon: 'zap',
    response: '🔥 Skor sementara:\n\n🇧🇷 Brasil 2 - 1 Jerman 🇩🇪\n⏱️ Menit 67\n⚽ Neymar (32\'), Vinicius (58\')\n⚽ Musiala (45+1\')\n📊 Penguasaan bola: 48% - 52%\n\n🇪🇸 Spanyol 0 - 0 Maroko 🇲🇦\n⏱️ Menit 23\n\n🇫🇷 Prancis 1 - 0 Senegal 🇸🇳\n⏱️ Menit 45\n⚽ Mbappé (38\')',
  },
  {
    id: 'predictions',
    label: 'Prediksi Hari Ini',
    icon: 'brain',
    response: '🧠 Prediksi Hari Ini:\n\n1. 🇧🇷 Brasil vs Jerman 🇩🇪\n   Peluang: Brasil 52% | Seri 26% | Jerman 22%\n   Analisis: Brasil diunggulkan berkat form ofensif yang konsisten.\n\n2. 🇦🇷 Argentina vs Maroko 🇲🇦\n   Peluang: Argentina 55% | Seri 25% | Maroko 20%\n   Analisis: Argentina dalam performa terbaik pasca juara dunia.\n\n3. 🇫🇷 Prancis vs Senegal 🇸🇳\n   Peluang: Prancis 60% | Seri 22% | Senegal 18%\n   Analisis: Kedalaman skuad Prancis menjadi faktor penentu.',
  },
  {
    id: 'schedule',
    label: 'Jadwal',
    icon: 'calendar',
    response: '📅 Jadwal Pertandingan Hari Ini:\n\n🕐 17:00 WIB - Brasil vs Jerman\n📍 Stadium MetLife, New York\n\n🕐 20:00 WIB - Spanyol vs Maroko\n📍 Stadium AT&T, Dallas\n\n🕐 23:00 WIB - Prancis vs Senegal\n📍 Stadium SoFi, Los Angeles\n\n📅 Besok:\n🕐 03:00 WIB - Inggris vs Belanda\n📍 Stadium Lumen, Seattle',
  },
  {
    id: 'standings',
    label: 'Klasemen Grup',
    icon: 'table',
    response: '🏆 Klasemen Grup A:\n\n1. 🇳🇱 Belanda    6 pts (+3)\n2. 🇪🇨 Ekuador    3 pts (0)\n3. 🇸🇳 Senegal    3 pts (-1)\n4. 🇶🇦 Qatar       0 pts (-2)\n\n🏆 Klasemen Grup B:\n\n1. 🏴󠁧󠁢󠁥󠁮󠁧󠁿 Inggris    6 pts (+4)\n2. 🇺🇸 USA        3 pts (+1)\n3. 🇮🇷 Iran       3 pts (-1)\n4. 🏴󠁧󠁢󠁷󠁬󠁳󠁿 Wales      0 pts (-4)',
  },
];

export const NEWS_ITEMS: NewsItem[] = [
  {
    id: '1',
    title: 'Neymar Kembali Gemilang di Piala Dunia',
    summary: 'Bintang Brasil itu mencetak gol indah dari tendangan bebas di menit 32.',
    time: '15 menit lalu',
  },
  {
    id: '2',
    title: 'Messi Umumkan Ini Piala Dunia Terakhirnya',
    summary: 'Kapten Argentina mengonfirmasi pensiun dari timnas setelah turnamen ini.',
    time: '1 jam lalu',
  },
  {
    id: '3',
    title: 'Jerman Terancam Gugur di Fase Grup',
    summary: 'Die Mannschaft harus menang di dua laga sisa untuk lolos ke babak 16 besar.',
    time: '2 jam lalu',
  },
];
